//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AppConfig) DeepCopyInto(out *AppConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AppConfig) DeepCopy() *AppConfig {
	if in == nil {
		return nil
	}
	out := new(AppConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *AppConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppConfigList) DeepCopyInto(out *AppConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppConfigList) DeepCopy() *AppConfigList {
	if in == nil {
		return nil
	}
	out := new(AppConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *AppConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppConfigSpec) DeepCopyInto(out *AppConfigSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVarKV, len(*in))
		copy(*out, *in)
	}
}

func (in *AppConfigSpec) DeepCopy() *AppConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AppConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AppConfigStatus) DeepCopyInto(out *AppConfigStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AppConfigStatus) DeepCopy() *AppConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AppConfigStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *EnvVarKV) DeepCopyInto(out *EnvVarKV) {
	*out = *in
}

func (in *EnvVarKV) DeepCopy() *EnvVarKV {
	if in == nil {
		return nil
	}
	out := new(EnvVarKV)
	in.DeepCopyInto(out)
	return out
}
